fix: fix ts-node
gemini-testing/testplane pull request #979
Opened 2024-07-29 12:14 UTC by Kabir-Ivan

2024-08-01 09:35 UTC, shadowusr requested changes

2024-08-01 13:44 UTC, Kabir-Ivan commented on src/utils/typescript.ts
> +                        allowJs: true,
Looks like it does.

2024-08-02 18:05 UTC, DudaGod commented on src/utils/typescript.ts
> +                        allowJs: true,
I deleted this field in my PR (I didn't find any problems), but I don't mind if you delete it before I do.

2024-08-05 10:41 UTC, shadowusr approved these changes

2024-08-05 11:06 UTC, merged