fix: fix typescript
gemini-testing/testplane pull request #995
Opened 2024-08-09 12:35 UTC by Kabir-Ivan

2024-08-15 15:33 UTC, shadowusr requested changes
Also I get these errors when trying to compile a test project:
![](https://i.imgur.com/JiG2M3b.png)

Another thing is that we probably need to specify "recommended" tsconfig in typescript.md in docs.

2024-08-15 15:33 UTC, shadowusr commented on src/browser-pool/limited-pool.ts
> +    reject: (value: any) => void;
Can't we use `unknown` to circumvent linter warnings here?

2024-08-15 15:33 UTC, shadowusr commented on src/browser-pool/per-browser-limited-pool.ts
> +    _browserPools: Record<string, LimitedPool>;
blank line

2024-08-15 15:33 UTC, shadowusr commented on src/browser-pool/pool.ts
> +export default Pool;
I'd avoid `export default` absolutely everywhere (at least in new files): https://t.me/why_not_export_default

This file may be named `types.ts` and contain named exports.

2024-08-15 15:33 UTC, shadowusr commented on src/runner/browser-env/vite/browser-modules/mocha/parser.ts
> +import Mocha from "mocha";
I guess you're importing it just for the types to load? Can't we do `import type {} from "mocha"` then?

2024-08-15 15:33 UTC, shadowusr commented on src/worker/runner/browser-agent.ts
> +    static create(opts: CreateBrowserAgentOpts): BrowserAgent {
blank line

2024-08-15 15:33 UTC, shadowusr commented on src/worker/runner/caching-test-parser.ts
> +    static create<T extends CachingTestParser>(
blank line

2024-08-15 15:33 UTC, shadowusr commented on test/src/browser-pool/index.js
> +const BasicPool = require("src/browser-pool/basic-pool").default;
I'd switch to named exports where possible, since we already have to change "default" in so many places. But that's optional, up to you.

2024-08-15 15:33 UTC, shadowusr commented on typings/global.d.ts
>  // eslint-disable-next-line @typescript-eslint/triple-slash-reference
optional: we may use multi-line eslint comment here like
`/* eslint-disable @... */`

`/* eslint-enable @... */`

If they don't break triple slash directives.

2024-08-15 16:43 UTC, Kabir-Ivan commented on typings/clear-require.d.ts
> +declare module "clear-require" {
No. There is no types package as I remember.

2024-08-15 16:50 UTC, Kabir-Ivan commented on package.json
> +    "@types/bluebird": "3.5.38",
We do, but can be fixed by rewriting a few more files

2024-09-02 15:40 UTC, shadowusr approved these changes

2024-09-02 15:57 UTC, KuznetsovRoman approved these changes

2024-09-02 23:02 UTC, shadowusr commented
Tested on a large project: https://nda.ya.ru/t/NGp9aTXW77yDqN

2024-09-02 23:05 UTC, merged